[package]
name = "cool_package"
version = "0.1.0"
edition = "2021"

[dependencies]
cool_collections = { path = "../cool_collections" }

ahash = { workspace = true }
derive_more = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
