[package]
name = "cool-compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bumpalo = "3.11"
lazy_static = "1.4"
llvm-sys = "150"
paste = "1.0"
rustc-hash = "1.1"
smallvec = { version = "1.10", features = ["const_generics", "const_new", "union"] }
unicode-ident = "1.0"
