[package]
name = "cool_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
cool_driver = { path = "../cool_driver" }
cool_package = { path = "../cool_package" }
cool_resolve = { path = "../cool_resolve" }

anyhow = { workspace = true }
clap = { workspace = true }
toml = { workspace = true }
