[package]
name = "cool_lexer"
version = "0.1.0"
edition = "2021"

[dependencies]
cool_arena = { path = "../cool_arena" }
cool_span = { path = "../cool_span" }
paste = "1.0"
once_cell = "1.17"
unicode-ident = "1.0"
