[package]
name = "cool_resolve"
version = "0.1.0"
edition = "2021"

[dependencies]
cool_arena = { path = "../cool_arena" }
cool_lexer = { path = "../cool_lexer" }
rustc-hash = "1.1"
smallvec = { version = "1.10", features = ["const_generics", "const_new", "union"] }
