[package]
name = "cool_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
cool_lexer = { path = "../cool_lexer" }
cool_span = { path = "../cool_span" }
smallvec = { version = "1.10", features = ["const_generics", "const_new", "union"] }
