[package]
name = "cool_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
cool_derive = { path = "../cool_derive" }
cool_lexer = { path = "../cool_lexer" }
cool_span = { path = "../cool_span" }

derive_more = { workspace = true }
