[package]
name = "cool_ir"
version = "0.1.0"
edition = "2021"

[dependencies]
cool_ast = { path = "../cool_ast" }
cool_collections = { path = "../cool_collections" }
cool_lexer = { path = "../cool_lexer" }
cool_resolve = { path = "../cool_resolve" }

[lints]
workspace = true
