<arithmetic_bin_op> ::= + | - | * | / | %

<rel_bin_op> ::= != | == | < | > | <= | >=

<bitwise_bin_op> ::= "|" | & | ^

<bin_op> ::= <arithmetic_bin_op>
           | <rel_bin_op>
           | <bitwise_bin_op>

<expr> ::= <ident>
         | <expr> <bin_op> <expr>
         | (<expr>)
