<primitive> ::= bool

<type> ::= <primitive>
         | <identifier>

<fn-argument> ::= <identifier>: <type>

<nonempty-fn-argument-list> ::= <fn-argument>
                            ::= <fn-argument>, <nonempty-fn-argument-list>

<fn-argument-list> ::= </>
                     | <nonempty-fn-argument-list>
                     | <nonempty-fn-argument-list>, 

<fn-expression> ::= fn(<fn-arguments>) {}

<nonempty-module> ::= <fn-expression>
                    | <fn-expression> <nonempty-module>

<module> ::= </>
           | <nonempty-module>

<bin_op> ::= + | - | * | /

<expr> ::= <ident>
       ::= 