[workspace]
members = [
    "cool_arena",
    "cool_ast",
    "cool_cli",
    "cool_codegen",
    "cool_collections",
    "cool_driver",
    "cool_lexer",
    "cool_parser",
    "cool_resolve",
    "cool_span",
]

[workspace.dependencies]
bumpalo = "3.13"
clap = { version = "4.3", features = ["derive"] }
colored = "2.0"
derive_more = "0.99"
inkwell = { version = "0.2", features = ["llvm16-0"] }
once_cell = "1.18"
paste = "1.0"
rustc-hash = "1.1"
smallstr = { version = "0.3", features = ["union"] }
smallvec = { version = "1.11", features = ["const_generics", "const_new", "union"] }
unicode-ident = "1.0"
