[workspace]
members = [
    "cool_arena",
    "cool_derive",
    "cool_driver",
    "cool_lexer",
    "cool_parser",
    "cool_span",
]
resolver = "2"

[workspace.dependencies]
derive_more = { version = "1.0.0-beta.3", features = ["full"] }
