[workspace]
members = [
    "cool_arena",
    "cool_ast",
    "cool_cli",
    "cool_codegen",
    "cool_collections",
    "cool_driver",
    "cool_lexer",
    "cool_parser",
    "cool_resolve",
    "cool_span",
]

[workspace.dependencies]
smallstr = { version = "0.3", features = ["union"] }
smallvec = { version = "1.10", features = ["const_generics", "const_new", "union"] }
